name: Build & Test

on:
  push

jobs:
  build:
    runs-on: macos-14
    name: Build and Test
    timeout-minutes: 10
    env:
      XC_SCHEME: 'pdfv-digio-ios-app'
      XC_PROJ: 'pdfv-digio-ios-app.xcodeproj'
      XC_DESTINATION: 'platform=iOS Simulator,name=iPhone 15 Pro'
      XC_TESTPLAN: 'UnitTestsPlan'

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Set Xcode Version
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable

      - name: Build and Test Project
        working-directory: './pdfv-digio-ios-app'
        run: |
          /usr/bin/xcodebuild test \
            -project "$XC_PROJ" \
            -scheme "$XC_SCHEME" \
            -testPlan  $XC_TESTPLAN \
            -destination "$XC_DESTINATION" \
            -resultBundlePath TestResults-${{ github.run_number }} \
            -skipPackagePluginValidation

      - name: Display & Upload Test Results
        uses: kishikawakatsumi/xcresulttool@v1
        if: failure()
        with:
          path: TestResults-${{ github.run_number }}.xcresult
          show-passed-tests: false
          show-code-coverage: false
